name: dotnet package

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Build
      shell: cmd
      run: build.bat
    - name: Test
      shell: cmd
      run: build\DBMAbout.exe
