on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: build
        uses: actions/checkout@v2
        run: |
          (Get-Content src\dbm\DBMInfo.vb) -replace 'Const GITHASH As String = ".*?"', ('Const GITHASH As String = "' + $Env:GITHUB_SHA.SubString(0, 8) + '"') | Set-Content src\dbm\DBMInfo.vb
          .\build.bat
          build\DBMAbout.exe
