name: dotnet package

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: SetHash
      run: (Get-Content src\dbm\DBMInfo.vb) -replace 'Const GITHASH As String = ".*?"', ('Const GITHASH As String = "' + $Env:CI_COMMIT_SHORT_SHA + '"') | Set-Content src\dbm\DBMInfo.vb
    - name: Build
      run: .\build.bat
    - name: Test
      run: build\DBMAbout.exe
